version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: starburger_backend
    command: sh -c "python manage.py migrate"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - staticfiles:/staticfiles
      - bundles:/bundles
      - media:/media
      - assets:/asses

  frontend:
    build:
      context: ./frontend
    container_name: starburger_frontend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always
    volumes:
      - staticfiles:/staticfiles
      - bundles:/bundles
      - media:/media
      - assets:/asses

  db:
    image: postgres:14-alpine
    container_name: starburger_db
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    restart: always

  nginx:
    image: nginx:1.18-alpine
    container_name: starburger_nginx
    depends_on:
      - db
    volumes:
      - staticfiles:/staticfiles
      - assets:/asses
      - bundles:/bundles
      - media:/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443


  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on: nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

volumes:
  staticfiles:
  bundles:
  media:
  conf:
  db:
