version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: starburger_backend
    command: sh -c "python manage.py migrate"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - staticfiles:/staticfiles
      - bundles:/bundles
      - media:/media
      - assets:/asses

  frontend:
    build:
      context: ./frontend
    container_name: starburger_frontend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: always
    volumes:
      - staticfiles:/staticfiles
      - bundles:/bundles
      - media:/media
      - assets:/asses

  db:
    image: postgres:14-alpine
    container_name: starburger_db
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    restart: always

  nginx:
    image: nginx:1.18-alpine
    container_name: starburger_nginx
    depends_on:
      - db
    volumes:
      - staticfiles:/staticfiles
      - assets:/asses
      - bundles:/bundles
      - media:/media
      - ./nginx/nginx_prod.conf:/etc/nginx/conf.d/default.conf
      - etc-letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    ports:
      - 80:80
      - 443:443

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --dry-run --no-eff-email -d burger-em.ru -v
    depends_on:
      - nginx
    volumes:
      - certbot-www:/var/www/certbot/:rw
      - etc-letsencrypt:/etc/letsencrypt

volumes:
  etc-letsencrypt:
  certbot-www:
  staticfiles:
  bundles:
  assets:
  media:
  conf:
  db:
