# Generated by Django 3.2.15 on 2023-03-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230306_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработан', 'Обработан'), ('Необработан', 'Необработан')], default='Необработан', max_length=15, verbose_name='Статус'),
        ),
    ]
