# Generated by Django 3.2.15 on 2023-03-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230306_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработан', 'Обработан'), ('Необработан', 'Необработан')], db_index=True, default='Необработан', max_length=15, verbose_name='Статус'),
        ),
    ]
