# Generated by Django 3.2.15 on 2023-03-06 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_ed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Звонили'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Начали готовить'),
        ),
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Зарегистрирован'),
        ),
    ]
