# Generated by Django 3.2.15 on 2023-03-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230306_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='called_ed_at',
            field=models.DateTimeField(blank=True, verbose_name='Звонили'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, verbose_name='Начали готовить'),
        ),
    ]
