# Generated by Django 3.2.15 on 2023-03-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lat',
            field=models.FloatField(default=37.617698, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='order',
            name='lon',
            field=models.FloatField(default=55.755864, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(default=37.617698, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lon',
            field=models.FloatField(default=55.755864, verbose_name='Долгота'),
        ),
    ]
