# Generated by Django 3.2.15 on 2023-03-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20230315_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='order_restaurant',
        ),
    ]
