# Generated by Django 3.2.15 on 2023-02-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_lastname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
