# Generated by Django 3.2.15 on 2023-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработан', 'Обработан'), ('Необработан', 'Необработан'), ('Готовится', 'Готовится')], db_index=True, default='Необработан', max_length=15, verbose_name='Статус'),
        ),
    ]
