# Generated by Django 3.2.15 on 2023-03-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
