# Generated by Django 3.2.15 on 2023-03-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_auto_20230315_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
        ),
    ]
