# Generated by Django 3.2.15 on 2023-03-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_alter_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='calleded_at',
            new_name='called_at',
        ),
    ]
